// <auto-generated />
using System;
using MailServiceApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MailServiceApi.Migrations
{
    [DbContext(typeof(MaileServiceDbContext))]
    partial class MaileServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MailServiceApi.Models.MessageBody", b =>
                {
                    b.Property<Guid>("MessageReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.HasKey("MessageReportId");

                    b.ToTable("MessageBodies");
                });

            modelBuilder.Entity("MailServiceApi.Models.MessageRecipient", b =>
                {
                    b.Property<Guid>("MessageReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("Recipient")
                        .HasColumnType("text");

                    b.HasKey("MessageReportId", "Recipient");

                    b.ToTable("MessageRecipients");
                });

            modelBuilder.Entity("MailServiceApi.Models.MessageReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FailedMessage")
                        .HasColumnType("text");

                    b.Property<string>("MessageFrom")
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MessageReports");
                });

            modelBuilder.Entity("MailServiceApi.Models.MessageBody", b =>
                {
                    b.HasOne("MailServiceApi.Models.MessageReport", "MessageReport")
                        .WithOne("MessageBody")
                        .HasForeignKey("MailServiceApi.Models.MessageBody", "MessageReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MessageReport");
                });

            modelBuilder.Entity("MailServiceApi.Models.MessageRecipient", b =>
                {
                    b.HasOne("MailServiceApi.Models.MessageReport", "MessageReport")
                        .WithMany("MessageRecipients")
                        .HasForeignKey("MessageReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MessageReport");
                });

            modelBuilder.Entity("MailServiceApi.Models.MessageReport", b =>
                {
                    b.Navigation("MessageBody");

                    b.Navigation("MessageRecipients");
                });
#pragma warning restore 612, 618
        }
    }
}
